### ISSUE TITLE
Wallet

### ISSUE THREAD

**Issue by CryptoRanger1** [letheanVPN/documentation#11]
Came across your project or this project n coin gecko.  I clicked on info to go to your website but there’s no website.   It gives an address to click on but that takes me to a page stating if website doesn’t load r under construction or something can’t recall then CLICK HERE which brings me to here.  

Any info or docs page would be nice and maybe a place I could download a wallet..

thank you

**Comment by bodane** [comment]
Hi @CryptoRanger1,

Apologies for the untimely response. The team is presently rebuilding the project hence it may be harder to get all the detail outside of github at the present time.

Once the software side is in a good working state you'll see alot more content up which will make getting to information alot easier. New whitepapers are also being re-written. Drafts have been written however will get a major update before being published.

You can keep up to speed with what Lethean is doing by referring to Github activities [here ](https://github.com/letheanVPN) and reaching the community on Discord (most active), Telegram or X if you have further questions.

The main lethean.io and lt.hn domains now both redirect to the documentation page [here ](https://lt.hn/index.html), which I believe you will have recently visited. Do let me if you find broken links anywhere and we'll keep note and resolve.

To get your wallet and chain daemons loaded up refer to here:

https://lt.hn/getting-started/wallet.html
https://lt.hn/getting-started/chain.html

The VPN section included in the documentation pages is not the present state and is being replaced by a new VPN solution which is currently very much in the early stages of testing however the project is always keen for testers and can be followed [here](https://github.com/letheanVPN/lvpn).
