### ISSUE TITLE
Pi2 Build Documentation

### ISSUE THREAD

**Issue by Snider** [letheanVPN/documentation#5]
https://github.com/letheanVPN/documentation/blob/0e093b0f57545adb2d6b04dca7c541f69d2d6ff4/docs/chain/build/pi2.yml#L1

**Comment by lavakush07** [comment]
Hey, I would like to work upon this issue..

**Comment by Snider** [comment]
Sweet, this one might be fun as the documentation is old.

but if I have to buy a Pi2; so be it :)

let me know if you get stuck, its what I'm here for :)
